BitcreditProtocol/Wildcat

Cargo.toml
src/credit/keys.rs
src/credit/mod.rs
src/credit/persistence.rs
src/keys/mod.rs
src/lib.rs
src/main.rs
src/swap.rs
src/utils.rs

introduce generic swap subsystem

swap subsystem

---

src/credit/keys.rs
src/credit/mod.rs
src/credit/quotes.rs
src/keys/mod.rs
src/main.rs

when a new quote keys is generated, the factory ensures that a correspondent maturing key that matures when the ebill matures is properly generated and stored in the maturing keys repository

refactor credit keys factory

---

Cargo.toml
src/credit/admin.rs
src/credit/quotes.rs
src/credit/web.rs
src/persistence/inmemory.rs
src/swap/service.rs
src/utils.rs

convert credit::quotes::Repository to async

async quotes repository

---

Cargo.toml
crates/bcr-wdc-key-client/Cargo.toml
crates/bcr-wdc-key-client/src/lib.rs
crates/bcr-wdc-key-service/Cargo.toml
crates/bcr-wdc-key-service/src/admin.rs
crates/bcr-wdc-key-service/src/factory.rs
crates/bcr-wdc-key-service/src/lib.rs
crates/bcr-wdc-key-service/src/main.rs
crates/bcr-wdc-key-service/src/persistence/inmemory.rs
crates/bcr-wdc-key-service/src/persistence/surreal.rs
crates/bcr-wdc-key-service/src/service.rs
crates/bcr-wdc-key-service/src/web.rs
crates/bcr-wdc-keys/src/lib.rs
crates/bcr-wdc-keys/src/persistence.rs
crates/bcr-wdc-quote-service/src/keys_factory.rs
crates/bcr-wdc-quote-service/src/persistence/inmemory.rs
crates/bcr-wdc-quote-service/src/persistence/surreal/keysets.rs
crates/bcr-wdc-webapi/src/keys.rs
crates/bcr-wdc-webapi/src/lib.rs

implements the new function pre_sign as a first step to
migrate and concentrate all the functions that deal with generating
wildcat's signing keys into a single service.

[bcr-wdc-key-service]: add pre_sign function

---

Cargo.toml
crates/bcr-wdc-quote-service/Cargo.toml
crates/bcr-wdc-quote-service/src/admin.rs
crates/bcr-wdc-quote-service/src/lib.rs
crates/bcr-wdc-quote-service/src/persistence/inmemory.rs
crates/bcr-wdc-quote-service/src/persistence/surreal.rs
crates/bcr-wdc-quote-service/src/quotes.rs
crates/bcr-wdc-quote-service/src/service.rs
crates/bcr-wdc-swap-service/Cargo.toml
crates/bcr-wdc-webapi/Cargo.toml
crates/bcr-wdc-webapi/src/quotes.rs

resolving isse #72

---

crates/bcr-wdc-ebpp/Cargo.toml
crates/bcr-wdc-ebpp/src/error.rs
crates/bcr-wdc-ebpp/src/lib.rs
crates/bcr-wdc-ebpp/src/onchain.rs

from esplora client to electrum client

[bcr-wdc-ebpp] refactor error and bdk_wallet Syncer

---

crates/bcr-wdc-swap-client/tests/swap.rs
crates/bcr-wdc-swap-service/Cargo.toml
crates/bcr-wdc-swap-service/src/error.rs
crates/bcr-wdc-swap-service/src/persistence/surreal.rs
crates/bcr-wdc-swap-service/src/service.rs
crates/bcr-wdc-treasury-service/Cargo.toml
crates/bcr-wdc-treasury-service/src/credit/mod.rs
crates/bcr-wdc-treasury-service/src/debit/service.rs
crates/bcr-wdc-treasury-service/src/error.rs
crates/bcr-wdc-treasury-service/src/persistence/surreal.rs
crates/bcr-wdc-utils/Cargo.toml
crates/bcr-wdc-utils/src/lib.rs
crates/bcr-wdc-utils/src/signatures.rs

make room for utils functions in signatures:
- put test functions in test_utils sub-module

[bcr-wdc-utils] add checks function for messages and proofs

---

Cargo.toml
crates/bcr-wdc-ebpp/Cargo.toml
crates/bcr-wdc-key-client/Cargo.toml
crates/bcr-wdc-key-service/Cargo.toml
crates/bcr-wdc-quote-service/Cargo.toml
crates/bcr-wdc-swap-client/Cargo.toml
crates/bcr-wdc-swap-service/Cargo.toml
crates/bcr-wdc-treasury-client/Cargo.toml
crates/bcr-wdc-treasury-service/Cargo.toml
crates/bcr-wdc-utils/Cargo.toml
crates/bcr-wdc-wallet-aggregator/Cargo.toml
crates/bcr-wdc-webapi/Cargo.toml
deny.toml

- add deny.toml config file for cargo deny tool
- fix cargo.toml files

[workspace] introduce cargo-deny

---

crates/bcr-wdc-ebpp/src/service.rs

cdk-payment-processor APIs are not very well though through IMHO. We are doing our best to avoid making unwanted or wrong payments

[bcr-wdc-ebpp] small refactor + more tests

---

crates/bcr-wdc-wallet-aggregator/src/web.rs

The API forwards the request to both crsat and sat subsystems and merges the two responses into a single one.

[bcr-wdc-wallet-aggregator] add /v1/restore API

---

Cargo.toml
crates/bcr-wdc-ebill-service/Cargo.toml
crates/bcr-wdc-ebill-service/src/lib.rs
crates/bcr-wdc-ebill-service/src/main.rs
crates/bcr-wdc-ebpp/src/service.rs
docker/ebill-service/config.toml

* Upgrades E-Bill deps to the latest 0.3.12
* Fix a clippy lint

Upgrade E-Bill to 0.3.12

---

crates/bcr-wdc-swap-client/src/lib.rs
crates/bcr-wdc-swap-client/tests/checkstate.rs
crates/bcr-wdc-swap-service/src/lib.rs
crates/bcr-wdc-swap-service/src/persistence/inmemory.rs
crates/bcr-wdc-swap-service/src/persistence/surreal.rs
crates/bcr-wdc-swap-service/src/service.rs
crates/bcr-wdc-swap-service/src/web.rs
crates/bcr-wdc-webapi/src/swap.rs

as in nut07
Users can send their Ys to check against the mint if their proofs are
spent or not

[swap] add check_state API

---

crates/bcr-wdc-key-service/src/persistence/surreal.rs

cdk00::BlindSignature serializes the field `keyset_id` renaming it as `id`, a name for a field that surrealdb does not like at all.
@stefanbitcr 
another piece of knowledge that is worth passing that I learned the hard way.
We know that SurrealDB uses serde::serialization/deserialization to convert values for its internal storage, and we also know it does not like serializing/deserializing a structure that has a field named `id` in it*.
If an error like the one in #169  pops up, have a look at the structure you are dealing with, see if it has a field named `id`, and if it does not, check out the code and look for the [`#[serde(rename = "id")]`](https://docs.rs/cashu/latest/src/cashu/nuts/nut00/mod.rs.html#237) macro.
\* if the field `id` is nested inside an inner structure surreal can …

[bcr-wdc-key-service] fix issue with surrealdb in storing signatures

---

crates/bcr-wdc-e2e-tests/src/clients.rs
crates/bcr-wdc-e2e-tests/src/main.rs
crates/bcr-wdc-quote-service/src/web.rs
crates/bcr-wdc-wallet-aggregator/example.config.toml
crates/bcr-wdc-webapi/src/bill.rs
crates/bcr-wdc-webapi/src/quotes.rs
crates/bcr-wdc-webapi/src/signatures.rs
crates/bcr-wdc-webapi/src/swap.rs
crates/bcr-wdc-webapi/src/wallet.rs
docker/swap-service/config.toml

**Changes**
- E2E test for mint info endpoint
- E2E test for swapping proofs and displaying V3 token afterward (can be imported into wallet)
- **Update incorrect port in Swap Service Docker config**
- Update resolve quote utoipa open api path
- Add missing Debug derives in web api for consistency

Fix and Test Swap Service

---

crates/bcr-wdc-ebpp/Cargo.toml
crates/bcr-wdc-ebpp/src/ebill.rs
crates/bcr-wdc-ebpp/src/error.rs
crates/bcr-wdc-ebpp/src/lib.rs

using recently added ebill-client APIs we implement the real EBillClient

[bcr-wdc-ebpp] implement EBillClient

---

.github/workflows/build.yml
Cargo.toml
crates/bcr-wdc-balance-collector/Cargo.toml
crates/bcr-wdc-balance-collector/src/error.rs
crates/bcr-wdc-balance-collector/src/lib.rs
crates/bcr-wdc-balance-collector/src/main.rs
crates/bcr-wdc-ebpp-client/Cargo.toml
crates/bcr-wdc-ebpp-client/src/lib.rs
crates/bcr-wdc-eiou-client/Cargo.toml
crates/bcr-wdc-eiou-client/src/lib.rs
crates/bcr-wdc-treasury-client/src/lib.rs
crates/bcr-wdc-webapi/src/wallet.rs
docker-compose.yml
docker/balance-collector/Dockerfile
docker/balance-collector/config.toml
docker/eiou-service/Dockerfile
docker/eiou-service/config.toml
justfile

balance collector is a service that periodically queries
treasury-service and eBill-payment-processor for their balance and
collects this data into a surrealDB time-series table

[bcr-wdc-balance-collector] add new service

---

crates/bcr-wdc-wallet-aggregator/Cargo.toml
crates/bcr-wdc-wallet-aggregator/src/lib.rs
docker/bff-dashboard-service/envoy.yaml
docker/bff-wallet-service/nginx.conf
docker/keycloak/realm-dev.json

- add domain to envoy cors config
- temp. add open cors config for testing
- fix inverted keycloak env vars

cors fixes

---

crates/bcr-wdc-treasury-client/src/lib.rs
crates/bcr-wdc-treasury-service/src/lib.rs
crates/bcr-wdc-wallet-aggregator/Cargo.toml
crates/bcr-wdc-wallet-aggregator/src/web.rs

Bug fix, Enhancement, Tests
___
- Fix redeem endpoint URL paths in treasury client and service
- Refactor swap type determination for better efficiency
- Add comprehensive test coverage for swap type logic
- Optimize keyset ID deduplication to reduce API calls
___
```mermaid
flowchart LR
A["Treasury Client"] -- "fix URL path" --> B["Treasury Service"]
C["Wallet Aggregator"] -- "refactor logic" --> D["Swap Type Detection"]
D -- "add tests" --> E["Test Coverage"]
C -- "optimize" --> F["Keyset ID Deduplication"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>lib.rs</strong><dd><code>Fix redeem endpoint URL …

redemption fixes

---

crates/bcr-wdc-ebill-service/src/lib.rs
crates/bcr-wdc-treasury-service/src/lib.rs
crates/bcr-wdc-wallet-aggregator/Cargo.toml
crates/bcr-wdc-wallet-aggregator/src/web.rs

Enhancement, Bug fix
___
- Add build time information to wallet aggregator description
- Fix import warnings in ebill service
- Update dependencies with required features
___
```mermaid
flowchart LR
A["Import Fix"] --> B["Ebill Service"]
C["Build Time"] --> D["Wallet Aggregator"]
E["Dependencies"] --> D
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>lib.rs</strong><dd><code>Fix unused import warnings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

add build_time to wildcat description

---

Cargo.toml
crates/bcr-wdc-ebill-service/src/error.rs
crates/bcr-wdc-ebill-service/src/lib.rs
crates/bcr-wdc-ebill-service/src/main.rs
crates/bcr-wdc-ebill-service/src/web.rs
crates/bcr-wdc-ebpp/Cargo.toml
crates/bcr-wdc-ebpp/src/persistence/inmemory.rs
crates/bcr-wdc-ebpp/src/service.rs
crates/bcr-wdc-quote-service/src/persistence/inmemory.rs
crates/bcr-wdc-swap-service/src/persistence/inmemory.rs
crates/bcr-wdc-treasury-service/src/persistence/inmemory.rs
crates/bcr-wdc-webapi/src/bill.rs
docker/ebill-service/config.toml

Enhancement
___
- Upgrade bcr-ebill-core dependency from v0.4.2 to v0.4.5
- Add new validation error types for file handling
- Refactor payment data structures in bill states
- Update service APIs with new parameters and methods
___
```mermaid
flowchart LR
A["Dependency Update"] --> B["bcr-ebill-core v0.4.5"]
B --> C["New Validation Errors"]
B --> D["Payment Data Refactoring"]
B --> E["Service API Updates"]
C --> F["File Handling Improvements"]
D --> G["Bill State Changes"]
E --> H["Enhanced Functionality"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td><strong>Cargo.toml</strong><dd><code>Update …

[dependencies] upgrade bcr-ebill-core to v0.4.5

---

.github/workflows/test.yml

Upgrades the rust cache in the `test` CI action, since that stopped working a while back.
(e.g. https://github.com/BitcreditProtocol/Wildcat/actions/runs/16565774571)
___
Other
___
- Update Rust cache action version in CI workflow
___
```mermaid
flowchart LR
oldCache["rust-cache@v2.7.5"] -- "upgrade" --> newCache["rust-cache@v2.8.0"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>test.yml</strong><dd><code>Upgrade rust-cache action version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

CI Cache fix

---

docker/base-image/Dockerfile

Other
___
- Upgrade Rust version from 1.87 to 1.89 in Docker base image
___
```mermaid
flowchart LR
A["Docker Base Image"] -- "upgrade" --> B["Rust 1.89-bookworm"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Upgrade Rust version in Docker image</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docker/base-image/Dockerfile
- Updated Rust base image from version 1.87 to 1.89
</details>
</td>
<td><a …

[docker]: upgrade rustc version

---

docker/ebill-service/config.toml

Add new E-Bill dev relay
___
Enhancement
___
- Update Nostr relay URL to new development endpoint
___
```mermaid
flowchart LR
oldRelay["Old Relay: bitcr-cloud-run-05"] -- "replaced with" --> newRelay["New Relay: bcr-relay-dev.minibill.tech"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>config.toml</strong><dd><code>Update Nostr relay endpoint configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docker/ebill-service/config.toml
<ul><li>Replace old relay URL with new development relay endpoint<br> …

Add new dev relay
